name: ManhuntRedux
version: ${project.version}
main: me.fallenmoons.manhuntredux.Main
api-version: 1.16
authors: [ FallenMoons ]
description: Manhunt Redux - Hunters vs Runners (Special thanks to dancemidget1, Hjoll, Brightglow, ColinSmoke, treester, anageds, JamFlam)
website: www.twitch.tv/fallenmoons
commands:
  hunter:
    description: Adds or removes a player from the "Hunters" team.
    usage: /<command> add/remove [PLAYER]
  runner:
    description: Adds or removes a player from the "Runners" team.
    usage: /<command> add/remove [PLAYER]
  clearteams:
    description: Clears all players from all teams!
    usage: /<command>
  round:
    description: Start/Stop and modify game rounds.
    usage: /<command> start/stop/view/countdown/leadtime [time]
  randomizeteams:
    description: Randomize all teams.
    usage: /<command>
  coordinates:
    description: Sends your current coordinates to your teammates!
    usage: /<command>
    aliases: [coords, c]
  all:
    description: Chat to everyone
    usage: /<command>
    aliases: [a]